### ISSUE TITLE
Is this repo now dead, can it be nuked?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/zarchive-xamarin-monodevelop-fsharp-addin#307]

**Comment by nosami** [comment]
Nope.. still used for Cycle 7 fixes

**Comment by jschiefer** [comment]
Excuse my ignorance, but what supersedes this repo?

**Comment by nosami** [comment]
@jschiefer The F# addin is now part of the monodevelop repo https://github.com/mono/monodevelop/tree/master/main/external/fsharpbinding

**Comment by dsyme** [comment]
this repo is archived, closing
