### ISSUE TITLE
Error in make when user PATH has spaces

### ISSUE THREAD

**Issue by lpvm** [fsharp/zarchive-xamarin-monodevelop-fsharp-addin#308]
When user PATH has some space, as in /home/user/clojure\ 4.0, the Makefile outputs an error

This patch seems to solve the issue:

--- Makefile    2016-09-22 15:36:57.343367793 +0100
+++ Makefile.path   2016-09-22 15:36:36.896366787 +0100
@@ -27,8 +27,8 @@
    case $$2 in _=_) dk="exit 1" ;; _k_) dk=: ;; *) dk="exit 1" ;; esac; \
    for dir in $(SUBDIRS); do \
        case $$dir in \
-       .) PATH=$(PATH):/Library/Frameworks/Mono.framework/Versions/Current/bin $(MAKE) $*-local || { final_exit="exit 1"; $$dk; };;\
-       _) (cd $$dir && PATH=$(PATH):/Library/Frameworks/Mono.framework/Versions/Current/bin $(MAKE) $_) || { final_exit="exit 1"; $$dk; };;\
-       .) PATH="$(PATH)":/Library/Frameworks/Mono.framework/Versions/Current/bin $(MAKE) $*-local || { final_exit="exit 1"; $$dk; };;\
-       _) (cd $$dir && PATH="$(PATH)":/Library/Frameworks/Mono.framework/Versions/Current/bin $(MAKE) $_) || { final_exit="exit 1"; $$dk; };;\
      esac \
  done
  $$final_exit

**Comment by nosami** [comment]
This repo is now redundant as the F# plugin is compiled as part of [monodevelop](https://github.com/mono/monodevelop)

Do you get the same error when building monodevelop?

**Comment by lpvm** [comment]
Hi,

No, I did not the error when building monodevelop.
I'll address this to monodevelop then.

Thank you Jason,

Luis

2016-09-23 14:28 GMT+01:00 Jason Imison <notifications@github.com>:

**Comment by dsyme** [comment]
archived repo, closing
